server {
    listen 80;
    listen [::]:80 default_server;
    client_max_body_size 30m;
    server_name _;
    client_header_timeout 1200s;
    client_body_timeout 1200s;
    send_timeout 1200s;
    keepalive_timeout 1200s;

    location ^~ /agent-static/ {
        # 使用 alias 替代 root，直接映射路径
        alias /usr/share/nginx/html/agent/dist/;

        # 可选：匹配特定文件后缀（如 js/css/png 等）
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|woff2|woff|map)$ {
            # 继承父级的 alias 配置
            expires 7d;
            add_header Cache-Control "public";
            try_files $uri $uri/ =404;
        }

        # 禁止访问隐藏文件（可选）
        location ~ /\. {
            deny all;
        }
    }

    location / {
        root    /usr/share/nginx/html/agent/dist;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html =404;
    }

    # 不进行重定向的路径
    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|js|css|woff|map)$ {
        root    /usr/share/nginx/html/agent/dist;
    }
}